import axios from './axios';

const REPORTS_STORAGE_KEY = 'egy_medichain_local_reports';

const REPORT_TYPE_LABELS = {
  inventory: 'Inventory Report',
  shipments: 'Shipments Report',
  compliance: 'Compliance Report',
  audit: 'Audit Report',
};

const PERFORMANCE_DATA = [
  { name: 'Jan', shipments: 120, deliveries: 115 },
  { name: 'Feb', shipments: 150, deliveries: 142 },
  { name: 'Mar', shipments: 180, deliveries: 175 },
  { name: 'Apr', shipments: 165, deliveries: 160 },
  { name: 'May', shipments: 200, deliveries: 195 },
  { name: 'Jun', shipments: 220, deliveries: 210 },
];

const createId = () => `local-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;

const loadLocalReports = () => {
  try {
    const stored = localStorage.getItem(REPORTS_STORAGE_KEY);
    if (!stored) return [];

    const parsed = JSON.parse(stored);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
};

const saveLocalReports = (reports) => {
  localStorage.setItem(REPORTS_STORAGE_KEY, JSON.stringify(reports));
};

const makeLocalReport = (data = {}) => {
  const type = data.type || 'inventory';
  const now = new Date().toISOString();
  const typeLabel = REPORT_TYPE_LABELS[type] || `${type} Report`;

  return {
    id: createId(),
    name: typeLabel,
    type,
    generatedBy: 'Demo Administrator',
    createdAt: now,
    size: '1.2 MB',
    status: 'ready',
  };
};

const getReportCount = (reports) => ({
  totalReports: reports.length,
  readyReports: reports.filter((report) => report.status === 'ready').length,
  pendingReports: reports.filter((report) => report.status !== 'ready').length,
  generatedToday: reports.filter((report) => new Date(report.createdAt).toDateString() === new Date().toDateString()).length,
});

const createDownloadBlob = (report) => {
  const csv = [
    ['Report Name', 'Type', 'Generated By', 'Created', 'Status'],
    [report.name || '', report.type || '', report.generatedBy || '', report.createdAt || '', report.status || ''],
  ]
    .map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(','))
    .join('\n');

  return new Blob([csv], { type: 'text/csv;charset=utf-8;' });
};

const shouldUseFallback = (error) => {
  const status = error?.status ?? error?.response?.status ?? 0;
  return status === 0 || status === 404 || status >= 500;
};

const getOfflineReports = (params = {}) => {
  const reports = loadLocalReports();
  const page = Number(params.page || 1);
  const limit = Number(params.limit || reports.length || 10);
  const filteredReports = reports.filter((report) => {
    if (!params.type) return true;
    return report.type === params.type;
  });

  const start = (page - 1) * limit;
  const end = start + limit;

  return {
    reports: filteredReports.slice(start, end),
    total: filteredReports.length,
  };
};

export const reportsApi = {
  // Get all reports
  getAll: async (params) => {
    try {
      return await axios.get('/reports', { params });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      const offline = getOfflineReports(params);
      return {
        success: true,
        data: offline,
        message: 'Offline reports loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Get report by id
  getById: async (id) => {
    try {
      return await axios.get(`/reports/${id}`);
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      const report = loadLocalReports().find((item) => item.id === id);
      return {
        success: true,
        data: report || null,
        message: 'Offline report loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Generate report
  generate: async (data) => {
    try {
      return await axios.post('/reports/generate', data);
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      const report = makeLocalReport(data);
      const reports = [report, ...loadLocalReports()].slice(0, 100);
      saveLocalReports(reports);

      return {
        success: true,
        data: report,
        message: 'Offline report generated',
        error: null,
        status: 200,
      };
    }
  },

  // Get report templates
  getTemplates: async () => {
    try {
      return await axios.get('/reports/templates');
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: Object.values(REPORT_TYPE_LABELS),
        message: 'Offline templates loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Download report
  download: async (id, format = 'pdf') => {
    try {
      return await axios.get(`/reports/${id}/download`, {
        params: { format },
        responseType: 'blob',
      });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      const report = loadLocalReports().find((item) => item.id === id) || makeLocalReport({ type: 'inventory' });
      return {
        success: true,
        data: createDownloadBlob(report),
        message: 'Offline download generated',
        error: null,
        status: 200,
      };
    }
  },

  // Schedule report
  schedule: async (data) => {
    try {
      return await axios.post('/reports/schedule', data);
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: data,
        message: 'Offline schedule saved',
        error: null,
        status: 200,
      };
    }
  },

  // Get scheduled reports
  getScheduled: async () => {
    try {
      return await axios.get('/reports/scheduled');
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: [],
        message: 'Offline schedule loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Delete scheduled report
  deleteScheduled: async (id) => {
    try {
      return await axios.delete(`/reports/scheduled/${id}`);
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: null,
        message: 'Offline schedule deleted',
        error: null,
        status: 200,
      };
    }
  },

  // Get inventory report
  getInventoryReport: async (params) => {
    try {
      return await axios.get('/reports/inventory', { params });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: getOfflineReports({ ...params, type: 'inventory' }),
        message: 'Offline inventory report loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Get shipment report
  getShipmentReport: async (params) => {
    try {
      return await axios.get('/reports/shipments', { params });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: getOfflineReports({ ...params, type: 'shipments' }),
        message: 'Offline shipment report loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Get compliance report
  getComplianceReport: async (params) => {
    try {
      return await axios.get('/reports/compliance', { params });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: getOfflineReports({ ...params, type: 'compliance' }),
        message: 'Offline compliance report loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Get financial report
  getFinancialReport: async (params) => {
    try {
      return await axios.get('/reports/financial', { params });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: getOfflineReports({ ...params, type: 'financial' }),
        message: 'Offline financial report loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Fetch report stats
  getStats: async () => {
    try {
      return await axios.get('/reports/stats');
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: getReportCount(loadLocalReports()),
        message: 'Offline stats loaded',
        error: null,
        status: 200,
      };
    }
  },

  // Fetch analytics
  getAnalytics: async (params) => {
    try {
      return await axios.get('/reports/analytics', { params });
    } catch (error) {
      if (!shouldUseFallback(error)) {
        throw error;
      }

      return {
        success: true,
        data: {
          performance: PERFORMANCE_DATA,
          period: params?.period || '30d',
        },
        message: 'Offline analytics loaded',
        error: null,
        status: 200,
      };
    }
  },
};

export default reportsApi;
